[feature/#14] 백엔드 베이스 코드 작성
woowa-techcamp-2021/deal-15 pull request #16
Opened 2021-07-13 13:33 UTC by momongss

- api, services 는 test 코드입니다.
- sample.env 파일은 src 안쪽에 있으면 dotenv 가 인식을 못해서 루트로 뺐습니다.

2021-07-13 16:48 UTC, TsooranKim requested changes
코드 검토후 수정바랍니다.

`routers/api/`와 `services/`은 골격만 있으면 되므로 비워주셔도 될 것 같습니다.
비우면 git에 staging이 되지 않겠지만 하지 않으셔도 괜찮을 것 같습니다.

2021-07-13 16:48 UTC, TsooranKim commented on server/src/bin/www
> +}
```suggestion
function onListening() {
  debug('Listening on port ' + config.port);
}
```

onListening 함수의 호출부에서 인자를 넘겨주지 않아서 실제 출력에는 `undefined`로 나오고 있습니다.
매개변수를 넘겨 받는 것 보다 그냥 `config.port`를 출력하는 것이 더 좋을 것 같습니다.

2021-07-13 16:48 UTC, TsooranKim commented on server/src/config/index.js
> +  env: process.env.NODE_ENV ? process.env.NODE_ENV : 'development',
```suggestion
  env: process.env.NODE_ENV || 'production',
```

삼항을 사용하는 것보다 `||`를 사용하는 것이 더 간단해 보입니다.
그리고 별도의 설정이 없을 경우 기본으로 `production`으로 설정되는 것이 방어적으로 맞다고 봅니다.

2021-07-13 16:48 UTC, TsooranKim commented on server/src/app.js
> +app.get('/api/test', apiTest.index());
이런식으로 별도 설정하지 말고 [`express.Router`](https://expressjs.com/en/4x/api.html#express.router)를 통해서 만든 router를 설정해 주셨으면 합니다.

2021-07-13 16:48 UTC, TsooranKim commented on server/src/bin/www
> +    onError();
선언은 `function onError(error)` 이러한데 실제 호출에서는 매개변수에 인자를 넘겨주지 않고 있습니다.

2021-07-13 16:48 UTC, TsooranKim commented on server/src/routes/api/test.js
> +};
[Router](https://expressjs.com/en/4x/api.html#router)를 사용해주셨으면 합니다.

2021-07-14 00:26 UTC, momongss commented on server/src/bin/www
> +}
아 저런 실수를 했군요.. 수정하겠습니다.

2021-07-14 01:21 UTC, momongss commented on server/src/bin/www
> +}
수정했습니다!

2021-07-14 01:22 UTC, momongss commented on server/src/app.js
> +app.get('/api/test', apiTest.index());
기본 골격만 남기고 코드 삭제했습니다.

2021-07-14 01:22 UTC, momongss commented on server/src/bin/www
> +    onError();
네 수정했습니다!

2021-07-14 01:23 UTC, TsooranKim commented on server/src/bin/www
> +  debug('Listening on ', config.port);
```suggestion
  debug('Listening on ' + config.port);
```

인자를 두개로 넘기시면 기본 ' '로 합쳐져서 출력이 됩니다.
현재는 공백이 2개로 출력됩니다.

2021-07-14 01:35 UTC, TsooranKim approved these changes
네 확인했습니다. 머지 해주시면 됩니다.

2021-07-14 01:35 UTC, merged