[feature/#29] 버튼 공통 컴포넌트 작성
woowa-techcamp-2021/deal-15 pull request #55
Opened 2021-07-17 11:48 UTC by momongss

버튼 공통 컴포넌트를 작성했습니다.
버튼 클릭 이벤트 핸들러는 테스트 코드입니다.

2021-07-18 06:05 UTC, TsooranKim requested changes
우선 전체적으로 style을 import 하는 것이 아닌 module로 불러와 주시기 바랍니다.

2021-07-18 06:11 UTC, TsooranKim reviewed
현재 global css에 box-sizing이 없어서 필요할때 마다 `box-sizing: border-box;`를 지정하고 있습니다.

별도의 issue로 global.scss에 `box-sizing`을 추가하는 것을 등록하겠습니다.

2021-07-18 06:19 UTC, TsooranKim requested changes
모든 button component가 div로 나타내지고 있습니다.
의미에 맞춰서 <button>을 사용하면 좋겠습니다.

2021-07-18 06:25 UTC, TsooranKim requested changes
```css
user-select: none;
cursor: pointer;
```

css에 `user-select: none` 을 넣어서 드레그를 막고 `cursor: pointer`를 넣어서 버튼 UX를 높히면 좋겠습니다.

2021-07-18 06:29 UTC, TsooranKim commented on client/src/styles/components/button/button-location.scss
> +}
```suggestion
.location {
  .btn-text {
    width: 78px;
  }
}
```

2021-07-18 06:31 UTC, TsooranKim requested changes
scss의 중첩 기능을 사용해보시는 것은 어떤가요?

2021-07-18 06:31 UTC, TsooranKim commented on client/src/styles/components/button/button-fab.scss
> +}
```suggestion
.fab {
  &.disable {
    background-color: $color-primary2;
  }
  
  &:not(.disable):hover {
    background-color: $color-primary3;
  }
}
```

2021-07-18 06:31 UTC, TsooranKim commented on client/src/styles/components/button/button-location.scss
> +}
```suggestion
.location {
  .btn-text {
    width: 78px;
  }
}
```

2021-07-18 06:47 UTC, TsooranKim commented on client/src/styles/components/button/button-status.scss
> +  width: 102px;
```suggestion
```

버튼에 미리 width가 정해져 있으면 안된다고 생각합니다.
width는 버튼을 배치하는 layout에 의해서 결정되야 합니다.

2021-07-18 08:32 UTC, momongss commented
> ```css
> user-select: none;
> cursor: pointer;
> ```
> 
> css에 `user-select: none` 을 넣어서 드레그를 막고 `cursor: pointer`를 넣어서 버튼 UX를 높히면 좋겠습니다.

네 좋습니다 반영하겠습니다.

2021-07-18 08:34 UTC, momongss commented on client/src/styles/components/button/button-fab.scss
> +}
css 만 오래 다뤘더니 scss 라는 걸 깜빡했네요. 중첩기능 활용하는 걸로 바꾸겠습니다.

2021-07-18 12:14 UTC, momongss commented on client/src/styles/components/button/button-location.scss
> +}
ㅎㅎ scss 를 css 처럼 썼었네요. 수정하겠습니다.

2021-07-18 12:16 UTC, momongss commented on client/src/styles/components/button/button-status.scss
> +  width: 102px;
layout 에 의해 결정된다는 건 내부 텍스트의 크기에 따라 달라져야한다는 말씀이신가요?

2021-07-18 14:37 UTC, TsooranKim commented on client/src/styles/components/button/button-status.scss
> +  width: 102px;
1차 적으로는 내부 텍스트에 의해서 변하는 것도 맞지만 외부의 layout(flex, grid 등)에 의해서 변하기도 해야합니다.

2021-07-18 14:52 UTC, TsooranKim requested changes

2021-07-18 14:52 UTC, TsooranKim commented on client/src/styles/components/button/reset.css
> +}
module.css를 사용할 때 이와 같이 tag 이름으로 넣게 되면 global 하게 적용됩니다.
예상하는 것 외의 모든 button tag에 style이 적용되게 되므로 사용하시면 안됩니다.
styles/ 디렉터리에 commom.module.scss를 만들고 그 안에 .button 블록을 만든다음에 사용하는 방식으로 진행하면 좋겠습니다.

2021-07-18 14:52 UTC, TsooranKim commented on client/src/styles/components/button/button-location.module.scss
> +}
```suggestion
```

module.css에서 최외각에 tag이름을 사용하면 안됩니다. global 하게 모든 곳에 적용되게 됩니다.

2021-07-19 05:02 UTC, TsooranKim approved these changes
넵 확인했습니다. 머지 부탁드립니다.

2021-07-19 05:02 UTC, merged