[feature/#30] text-input 공통 컴포넌트 작성
woowa-techcamp-2021/deal-15 pull request #57
Opened 2021-07-18 06:16 UTC by momongss

- text-input 공통 컴포넌트입니다.
- 컴포넌트 사용 방법은 pages/text-input-test-page.js 테스트 코드를 참조하시면 좋겠습니다.

2021-07-18 06:41 UTC, TsooranKim requested changes
scss 중첩기능을 #55 에서 언급해 드린 것과 같은 의견입니다.

2021-07-18 06:41 UTC, TsooranKim commented on client/src/styles/components/text-input/text-input.scss
> +}
```suggestion
```

이미 reset.css에 의해서 body의 margin은 0이 아닌가요?

2021-07-18 06:41 UTC, TsooranKim commented on client/src/components/text-input/text-input.js
> +import '@/styles/components/text-input/text-input.scss';
```suggestion
import styles from '@/styles/components/text-input/text-input.module.scss';
```

#55 에서 언급한 것과 같이 module.scss를 사용해주시기 바랍니다.

2021-07-18 07:40 UTC, momongss commented on client/src/styles/components/text-input/text-input.scss
> +}
아 그렇네요. 수정하겠습니다.

2021-07-18 07:52 UTC, momongss commented on client/src/components/text-input/text-input.js
> +import '@/styles/components/text-input/text-input.scss';
넵. 수정했습니다. 다른 부분들도 그렇게 수정하겠습니다.

2021-07-18 14:56 UTC, TsooranKim commented on client/src/index.js
> +import TestPage from '@/pages/text-input-test-page.js';
#55 와 merge 하면서 conflict가 나게 될겁니다.

2021-07-19 05:58 UTC, TsooranKim commented on client/src/index.js
> +// import TestPage from '@/pages/text-input-test-page.js';
```suggestion
// import TestPage from '@/pages/';
```

다른 작업에서 충돌이 나지 않게 이것만 수정해주시면 될 것 같습니다.

2021-07-19 06:02 UTC, TsooranKim approved these changes
고생하셨습니다~ 머지 바랍니다.

2021-07-19 06:02 UTC, merged